# Generated by Django 5.1.4 on 2025-03-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_list_unique_list_name_per_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('name', 'its_List', 'is_checked', 'created_at'), name='unique_list_name_per_list'),
        ),
    ]
