# Generated by Django 5.1.4 on 2025-03-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_remove_task_unique_list_name_per_list_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='unique_task_name_per_list',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_checked',
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('name', 'its_List', 'created_at'), name='unique_task_name_per_list'),
        ),
    ]
