# Generated by Django 5.1.4 on 2025-03-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_remove_task_unique_task_name_per_list_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='unique_task_name_per_list',
        ),
        migrations.AddField(
            model_name='task',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('name', 'its_List', 'is_checked', 'created_at'), name='unique_task_name_per_list'),
        ),
    ]
