# Generated by Django 5.1.4 on 2025-03-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_remove_task_unique_task_name_per_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(max_length=13),
        ),
    ]
